#!/usr/bin/env python
from trabajo_colaborativo.admin import Administrador
import rospy


def inicia_nodo():
    try:
        rospy.init_node('admin')
        moverse = Administrador()
        moverse.run()
    except rospy.ROSInterruptException:
        rospy.logerr("Error inicializando el nodo o llamando al servicio")



if __name__ == "__main__":
    inicia_nodo()