#!/usr/bin/env python
import rospy
from sac.sac import main
# from sac.continue_learning import main



try:

   main("pusher-v1")
        
except rospy.ROSInterruptException:
    rospy.logerr("Something went wrong or you pressed CTRL +C ...")




