#!/usr/bin/env python
import rospy
from sac.model_tester import main
# from sac.continue_learning import main



try:

   main()
        
except rospy.ROSInterruptException:
    rospy.logerr("Something went wrong or you pressed CTRL +C ...")




