#!/usr/bin/env python
import rospy
from ur5e_perception.collect_dataset import ImageCollector

# from sac.continue_learning import main



try:
   rospy.init_node("image_collection")
   collector = ImageCollector()

   collector.collect_images_test(50)
   rospy.signal_shutdown("all images collected")

        
except rospy.ROSInterruptException:
    rospy.logerr("Something went wrong or you pressed CTRL +C ...")




