#!/usr/bin/env python
from trabajo_colaborativo.cinta import Cinta
import rospy


def inicia_nodo():
    try:
        rospy.init_node('cinta')
        moverse = Cinta()
        moverse.run()
    except rospy.ROSInterruptException:
        rospy.logerr("Error inicializando el nodo o llamando al servicio")



if __name__ == "__main__":
    inicia_nodo()