#!/usr/bin/env python
from trabajo_colaborativo.robot_movil import Robobo
import rospy


def inicia_nodo():
    try:
        rospy.init_node('robobo1')
        moverse = Robobo("/robot/rob1")
        moverse.run()
    except rospy.ROSInterruptException:
        rospy.logerr("Error inicializando el nodo o llamando al servicio")



if __name__ == "__main__":
    inicia_nodo()